class_name DialogIds

enum Id {
	RESULT_DIALOG,
	SETTING_DIALOG,
	SKILL_UPGRADE_DIALOG,
	SKILL_RESET_CONFIRMATION_DIALOG,
	SKILL_NOT_AFFORDABLE_DIALOG,
	DEVELOPER_CONSOLE_DIALOG,
	MAIN_MENU_DIALOG,
	CREDITS_DIALOG,
	LEADERBOARD_DIALOG,
	ZONE_EDITOR_MENU_DIALOG,
	MINI_MAP_DIALOG,
}

static func id_to_name( id: DialogIds.Id ) -> String:
	match id:
		DialogIds.Id.RESULT_DIALOG:
			return "RESULT_DIALOG"
		DialogIds.Id.SETTING_DIALOG:
			return "SETTING_DIALOG"
		DialogIds.Id.SKILL_UPGRADE_DIALOG:
			return "SKILL_UPGRADE_DIALOG"
		DialogIds.Id.SKILL_RESET_CONFIRMATION_DIALOG:
			return "SKILL_RESET_CONFIRMATION_DIALOG"
		DialogIds.Id.SKILL_NOT_AFFORDABLE_DIALOG:
			return "SKILL_NOT_AFFORDABLE_DIALOG"
		DialogIds.Id.DEVELOPER_CONSOLE_DIALOG:
			return "DEVELOPER_CONSOLE_DIALOG"
		DialogIds.Id.MAIN_MENU_DIALOG:
			return "MAIN_MENU_DIALOG"
		DialogIds.Id.CREDITS_DIALOG:
			return "CREDITS_DIALOG"
		DialogIds.Id.LEADERBOARD_DIALOG:
			return "LEADERBOARD_DIALOG"
		DialogIds.Id.ZONE_EDITOR_MENU_DIALOG:
			return "ZONE_EDITOR_MENU_DIALOG"
		DialogIds.Id.MINI_MAP_DIALOG:
			return "MINI_MAP_DIALOG"
		_:
			return "[UNKNOWN DIALOG]"
