name: 📱 iOS - 📦 Archive
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      summary_style:
        description: 'The style for the summary'
        default: 'full'
        required: false
        type: string

jobs:
  sign:
    runs-on: macos-15
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: Create variables
        run: |
          PROJECT=${{ vars.PROJECT }}
          BUILD_TYPE="ios"
          LATEST_FILE="${PROJECT}-${BUILD_TYPE}-latest.txt"
          S3_LATEST_FILE="s3://artifacts.omnimad.net/${PROJECT}/${LATEST_FILE}"
          APP_TO_SIGN="${PROJECT}-${BUILD_TYPE}/fiiish-v3.app"
          ARCHIVE_TO_SIGN="${PROJECT}-${BUILD_TYPE}/${PROJECT}-${BUILD_TYPE}.xcarchive"
          #
          # put into github env
          #
          {
            echo "PROJECT=${PROJECT}"
            echo "BUILD_TYPE=${BUILD_TYPE}"
            echo "LATEST_FILE=${LATEST_FILE}"
            echo "S3_LATEST_FILE=${S3_LATEST_FILE}"
            echo "APP_TO_SIGN=${APP_TO_SIGN}"
            echo "ARCHIVE_TO_SIGN=${ARCHIVE_TO_SIGN}"
          } >> "$GITHUB_ENV"

      - name: Get latest reference
        run: |
          #
          # get latest info
          #
          aws s3 cp ${{ env.S3_LATEST_FILE }} ${{ env.LATEST_FILE }}
          # cat ${{ env.LATEST_FILE }}
          LATEST=$(cat "${{ env.LATEST_FILE }}")
          #
          # split into parts
          #
          ARCHIVE_FOLDER=$( dirname "${LATEST}" )
          ARCHIVE_NAME=$( basename "${LATEST}" .tgz )
          ARCHIVE_EXT=.tgz
          #
          # combine
          #
          ARCHIVE_FILE="${ARCHIVE_NAME}${ARCHIVE_EXT}"
          S3_ARCHIVE_FILE="s3://artifacts.omnimad.net/${LATEST}"
          SIGNED_ARCHIVE_FILE="${ARCHIVE_NAME}-signed.tgz"
          SIGNED_S3_ARCHIVE_FILE="s3://artifacts.omnimad.net/${ARCHIVE_FOLDER}/${SIGNED_ARCHIVE_FILE}"
          #
          # put into github env
          #
          {
            echo "ARCHIVE_FILE=${ARCHIVE_FILE}"
            echo "S3_ARCHIVE_FILE=${S3_ARCHIVE_FILE}"
            echo "SIGNED_ARCHIVE_FILE=${SIGNED_ARCHIVE_FILE}"
            echo "SIGNED_S3_ARCHIVE_FILE=${SIGNED_S3_ARCHIVE_FILE}"
          } >> "$GITHUB_ENV"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"

      - name: Download artifact
        run: |
          aws s3 cp ${{ env.S3_ARCHIVE_FILE }} ${{ env.ARCHIVE_FILE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"

      - name: Unpack artifact
        run: |
          tar xzvf ${{ env.ARCHIVE_FILE }}
          find ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}
          VERSION=$(cat ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}/version.txt)
          BUILD_NUMBER=$(cat ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}/build_number.txt)
          {
            echo "VERSION=${VERSION}"
            echo "BUILD_NUMBER=${BUILD_NUMBER}"
          } >> $GITHUB_ENV

      - name: Prepare keychain
        run: |
          keychain_password="$(openssl rand -hex 32)"
          security create-keychain -p "${keychain_password}" "the-keychain"
          echo "${{ secrets.APPLE_CODESIGN_CERT }}" | base64 --decode > cert.p12
          md5 < cert.p12
          keychain_db="${HOME}/Library/Keychains/the-keychain-db"
          security import cert.p12 -k "${keychain_db}" -P "${{ secrets.APPLE_CODESIGN_CERT_PASSWORD }}" -T "$(command -v codesign)"
          security set-key-partition-list -S "apple-tool:,apple:" -s -k "${keychain_password}" "${keychain_db}"
          security default-keychain -d "user" -s "${keychain_db}"
          security find-identity -v

      - name: Install AppStore key
        run: |
          mkdir -p ~/.appstoreconnect/private_keys/
          echo ${{ secrets.APP_STORE_API_PRIVATE_KEY }} | base64 -d -o ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8

      - name: Install provisioning profile
        run: |
          mkdir -p "${HOME}/Library/MobileDevice/Provisioning Profiles"
          echo -n ${{ secrets.APPLE_PROVISIONING_PROFILE }} | base64 -d -o "${HOME}/Library/MobileDevice/Provisioning Profiles/ghfiiishv320250402.mobileprovision"
          find ~/Library/MobileDevice

#      - name: Sign .xcarchive
#        id: sign0
#        continue-on-error: true
#        run: |
#          ping -c 5 time.apple.com
#          codesign -s ${{ secrets.CODESIGN_CERT_IDENTITY }} -f -v --timestamp --options runtime ${{ env.ARCHIVE_TO_SIGN }}
#        timeout-minutes: 10

      - name: Archive .ipa
        run: |
          xcodebuild -version
          find .
          echo ${{ vars.EXPORT_OPTIONS_PLIST }} |base64 -d > export_options.plist
          cat export_options.plist
          mkdir -p ../signed/${{ env.PROJECT }}-${{ env.BUILD_TYPE }}
          xcodebuild \
            -exportArchive \
            -archivePath ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}.xcarchive \
            -exportOptionsPlist export_options.plist \
            -exportPath ../signed/${{ env.PROJECT }}-${{ env.BUILD_TYPE }} # \
            # -authenticationKeyID ${{ secrets.APPSTORE_API_KEY_ID }} \
            # -authenticationKeyIssuerID ${{ secrets.APPSTORE_ISSUER_ID }} \
            # -allowProvisioningUpdates

        working-directory: ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}

      - name: Copy extra info
        run: |
          cp version.txt ../signed/${{ env.PROJECT }}-${{ env.BUILD_TYPE }}/
          cp build_number.txt ../signed/${{ env.PROJECT }}-${{ env.BUILD_TYPE }}/

        working-directory: ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}

      - name: Upload archive
        run: |
          cd signed
          tar czvf ${{ env.SIGNED_ARCHIVE_FILE }} ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}
          aws s3 cp ${{ env.SIGNED_ARCHIVE_FILE }} ${{ env.SIGNED_S3_ARCHIVE_FILE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"

      - name: Create Summary
        if: always()
        run: |
          if [[ "${{ inputs.summary_style }}" == "skip" ]]
          then
            echo "Skipping summary"
          elif [[ "${{ inputs.summary_style }}" == "minimal" ]]
          then
            {
              echo "|                        |                                   |"
              echo "| :--------------------- | --------------------------------: |"
              echo "| VERSION                | \`${{ env.VERSION }}\`            |" 
              echo "| BUILD_NUMBER           | \`${{ env.BUILD_NUMBER }}\`       |" 
            } >> "$GITHUB_STEP_SUMMARY"
          else
            {
              echo "|                        |                                   |"
              echo "| :--------------------- | --------------------------------: |"
              echo "| ARCHIVE_FILE           | ${{ env.ARCHIVE_FILE }}           |"
              echo "| S3_ARCHIVE_FILE        | ${{ env.S3_ARCHIVE_FILE }}        |"
              echo "| SIGNED_ARCHIVE_FILE    | ${{ env.SIGNED_ARCHIVE_FILE }}    |"
              echo "| SIGNED_S3_ARCHIVE_FILE | ${{ env.SIGNED_S3_ARCHIVE_FILE }} |"
              echo "| VERSION                | \`${{ env.VERSION }}\`            |" 
              echo "| BUILD_NUMBER           | \`${{ env.BUILD_NUMBER }}\`       |" 
            } >> "$GITHUB_STEP_SUMMARY"
          fi
