name: Build Unity WebGL on push
on: 
  workflow_dispatch:
  push:
    tags:
      # - "v*"
    paths:
      - unity/**

jobs:
  build:
    runs-on: ubicloud-standard-16
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            unity
          fetch-depth: 1
      - name: Setup Unity
        uses: RageAgainstThePixel/unity-setup@v1
        # with:
          # version-file: 'path/to/your/ProjectSettings.ProjectVersion.txt'
          # unity-version: ${{ matrix.unity-versions }} # overrides version in version-file
          build-targets: webgl
          modules: webgl

#      - name: Verify setup
#        run: |
#          godot --version
#
#      - name: Fix version info
#        run: |
#          .github/helpers/update_version_info.sh Web-demo
#
#      - name: Export WebGL
#        run: |
#          cd godot
#          mkdir -p export/webgl-demo
#          godot --headless --export-debug Web-demo export/webgl-demo/fiiish-v3.html --quit || exit 0
#
#      - name: Check result
#        run: |
#          cd godot
#          find export
#
#      - name: Update alpha
#        run: |
#          cd godot
#          aws s3 sync export/webgl-demo/ s3://games.omnimad.net/alpha/fiiish-v3/
#          aws cloudfront create-invalidation --distribution-id E323IOZK579VPC --paths "/alpha/fiiish-v3/*"
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: "eu-west-1"
