name: Build & Update Web - classic
run-name: Build & Update Web classic by @${{ github.actor }}

on: 
  workflow_dispatch:
#  push:
#    paths:
#      - godot/**
#      - .github/workflows/**

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: DISABLED
        run: |
          echo "web-classic is DISABLED"
          exit 1

  build:
    needs: [disabled]
    uses: ./.github/workflows/build.yaml
    with:
      build_type: 'web-classic'
    secrets: inherit

  update_web:
    needs: [build]
    uses: ./.github/workflows/update_web.yaml
    with:
      build_type: 'web-classic'
      s3_archive: ''
    secrets: inherit

