on: 
  workflow_dispatch:
  push:
    tags:
      # - "v*"
    paths:
      - godot/**

jobs:
  build:
    runs-on: ubicloud-standard-4
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            godot
          fetch-depth: 1
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.3.0
          use-dotnet: false
          include-templates: true
      - name: Verify setup
        run: |
          godot --version

      - name: Export WebGL
        run: |
          cd godot
          godot --headless --export-debug Web export/web/fiiish-v3.html --quit || exit 0

      - name: Check result
        run: |
          cd godot
          find export
