name: Build WebGL on push
on: 
  workflow_dispatch:
  push:
    tags:
      # - "v*"
    paths:
      - godot/**

jobs:
  build:
    runs-on: ubicloud-standard-4
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            godot
          fetch-depth: 1
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.4.0
          use-dotnet: false
          include-templates: true
      - name: Verify setup
        run: |
          godot --version

      - name: Fix version info
        run: |
          .github/helpers/update_version_info.sh Web-demo

      - name: Import project
        run: |
          cd godot
          godot --headless --quit || exit 0

      - name: Export WebGL
        run: |
          cd godot
          mkdir -p export/webgl-demo
          godot --headless --export-debug Web-demo export/webgl-demo/fiiish-v3.html --quit || exit 0

      - name: Check result
        run: |
          cd godot
          find export

      - name: Update alpha
        run: |
          cd godot
          aws s3 sync export/webgl-demo/ s3://games.omnimad.net/alpha/fiiish-v3/
          aws cloudfront create-invalidation --distribution-id E323IOZK579VPC --paths "/alpha/fiiish-v3/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
