name: Push latest macOS to itchio
on: 
  workflow_dispatch:
#  push:
#    tags:
#      - "v*"
#    # We always build on a tag
#    # paths:
#    #  - godot/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: Create variables
        run: |
          PROJECT=fiiish-v3
          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV
          BUILD_TYPE="macOS"
          echo "BUILD_TYPE=${BUILD_TYPE}" >> $GITHUB_ENV
          LATEST_FILE=${PROJECT}-${BUILD_TYPE}-latest.txt
          echo "LATEST_FILE=${LATEST_FILE}" >> $GITHUB_ENV
          S3_LATEST_FILE=s3://artifacts.omnimad.net/${PROJECT}/${LATEST_FILE}
          echo "S3_LATEST_FILE=${S3_LATEST_FILE}" >> $GITHUB_ENV

      - name: Download latest from S3
        run: |
          aws s3 cp ${{ env.S3_LATEST_FILE }} ${{ env.LATEST_FILE }}
          cat ${{ env.LATEST_FILE }}
          LF=s3://artifacts.omnimad.net/$(cat ${{ env.LATEST_FILE }} )
          aws s3 cp ${LF} .
          # or basename?
          TGZ=$(echo ${LF} |rev|cut -d'/' -f1 |rev)
          cd fiiish-v3-${{ env.BUILD_TYPE }}
          find .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
