name: Sign macOS
on: 
  workflow_dispatch:
  #push:
  #  tags:
  #    - "v*"
    # We always build on a tag
    # paths:
    #  - godot/**

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: Create variables
        run: |
          PROJECT=fiiish-v3
          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV
          BUILD_TYPE="macOS"
          echo "BUILD_TYPE=${BUILD_TYPE}" >> $GITHUB_ENV
          LATEST_FILE=${PROJECT}-${BUILD_TYPE}-latest.txt
          echo "LATEST_FILE=${LATEST_FILE}" >> $GITHUB_ENV
          S3_LATEST_FILE=s3://artifacts.omnimad.net/${PROJECT}/${LATEST_FILE}
          echo "S3_LATEST_FILE=${S3_LATEST_FILE}" >> $GITHUB_ENV

      - name: Get latest reference
        run: |
          aws s3 cp ${{ env.S3_LATEST_FILE }} ${{ env.LATEST_FILE }}
          cat ${{ env.LATEST_FILE }}
          LATEST=$(cat ${{ env.LATEST_FILE }})
          ARCHIVE_FILE=$( echo ${LATEST} |cut -d'/' -f 3 )
          echo "ARCHIVE_FILE=${ARCHIVE_FILE}" >> $GITHUB_ENV
          S3_ARCHIVE_FILE=s3://artifacts.omnimad.net/${ARCHIVE_FILE}
          echo "S3_ARCHIVE_FILE=${S3_ARCHIVE_FILE}" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"

      - name: Download artifact
        run: |
          aws s3 cp ${{ env.S3_ARCHIVE_FILE }} ${{ env.ARCHIVE_FILE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"

      - name: Unpack artifact
          tar xzvf ${{ env.ARCHIVE_FILE }}
          find ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}

      - name: Create Summary
        if: always()
        run: |
        echo "| ARCHIVE_FILE | ${{ env.ARCHIVE_FILE }} |" >> $GITHUB_STEP_SUMMARY
        echo "| S3_ARCHIVE_FILE | ${{ env.S3_ARCHIVE_FILE }} |" >> $GITHUB_STEP_SUMMARY

#      - name: Upload -> Download artifact
#        run: |
#          cd godot/export
#         echo ${{ env.VERSION }} > ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}/version.txt
#         tar czvf ${{ env.ARCHIVE_FILE }} ${{ env.PROJECT }}-${{ env.BUILD_TYPE }}
#         aws s3 cp ${{ env.ARCHIVE_FILE }} ${{ env.S3_ARCHIVE_FILE }}
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_DEFAULT_REGION: "eu-west-1"


#      - name: Create Summary
#        if: always()
#        run: |
##          echo "| COMMIT_HASH      | ${{ env.COMMIT_HASH }}     |" >> $GITHUB_STEP_SUMMARY
##          echo "| :----------- | ---------------------: |" >> $GITHUB_STEP_SUMMARY
##          echo "| COMMIT_DATE      | ${{ env.COMMIT_DATE }}     |" >> $GITHUB_STEP_SUMMARY
##          echo "| ARCHIVE_FILE      | ${{ env.ARCHIVE_FILE }}     |" >> $GITHUB_STEP_SUMMARY
#          echo "| BUILD_TYPE      | ${{ env.BUILD_TYPE }}     |" >> $GITHUB_STEP_SUMMARY
##          echo "| BINARY      | ${{ env.BINARY }}     |" >> $GITHUB_STEP_SUMMARY
#          echo "| LATEST_FILE      | ${{ env.LATEST_FILE }}     |" >> $GITHUB_STEP_SUMMARY
##          echo "| S3_ARCHIVE_FILE      | \`${{ env.S3_ARCHIVE_FILE }}\`     |" >> $GITHUB_STEP_SUMMARY
#          echo "| S3_LATEST_FILE      | \`${{ env.S3_LATEST_FILE }}\`     |" >> $GITHUB_STEP_SUMMARY
##          echo "| VERSION      | \`${{ env.VERSION }}\`     |" >> $GITHUB_STEP_SUMMARY

